FROM node:18

WORKDIR /app

RUN npm install -g pnpm

COPY package.json pnpm-lock.yaml ./

RUN pnpm install --ignore-scripts

COPY . .

ENV PATH="/app/node_modules/.bin:$PATH"

EXPOSE 3000

CMD ["pnpm", "dev"]
