<script setup lang="ts">

</script>

<template>
  <div class="text-primary dark:text-white w-8/12 m-auto pb-24">
    <br/><br/><h2 class="text-2xl font-bold underline">Définitions</h2><br/>
    <br> <p><strong class="underline uppercase">LE PRESTATAIRE</strong> :<br> AS-Turing est une société immatriculée au
      registre du commerce et des sociétés de Libourne sous le numéro 434 000&nbsp;782.</p>
    <p>Dans les présentes conditions générales de vente, est dénommée le <strong class="underline uppercase">CLIENT</strong> ou <strong class="underline uppercase">le prospect</strong>. Les présentes conditions générales de vente sont ci-après dénommées « les Conditions Générales ».</p>
    <p>Pour l'interprétation et la mise en œuvre des présentes Conditions Générales, il est convenu que les termes ci-après seront définis de la façon suivante :</p>
    <br><p><strong class="underline uppercase">Prestation </strong>:<br> désigne ci-après l'objet de la vente effectuée
    par
      AS-Turing. La <strong class="underline uppercase">prestation</strong> peut désigner un ensemble de <strong class="underline uppercase">prestation</strong>s de services tel qu'un conseil, une mise à disposition d'un savoir-faire, &nbsp;une <strong class="underline uppercase">prestation</strong> intellectuelle, la conception d'un <strong class="underline uppercase">site web</strong>, d’un extranet ou d'une application métier, etc.</p>
    <br><p><strong class="underline uppercase">Site Web ou Internet </strong>:<br> désigne l'ensemble de pages
    composées de
      textes, d'images et le cas échéant d'éléments multimédia, accessible par une adresse URL et hébergée sur le disque dur d'un serveur permettant des accès multiples et simultanés via le réseau Internet.</p>
    <br><p><strong class="underline uppercase">Sources </strong>:<br> désigne le contenu élémentaire nécessaire à la
      création d'une <strong class="underline uppercase">prestation</strong> immatérielle : textes, images et sons pour un site Internet, documents comptables pour une solution de comptabilité, etc. Sauf mention contraire, la fourniture des <strong class="underline uppercase">sources</strong> est à la charge du <strong class="underline uppercase">CLIENT</strong>.</p>
    <br><p><strong class="underline uppercase">Cahier des charges </strong>:<br> désigne le document fourni par le <strong
        class="underline uppercase">CLIENT</strong>, ou réalisé en collaboration avec AS-Turing contre rémunération, décrivant le plus explicitement possible le contenu de la <strong class="underline uppercase">prestation</strong> attendue et des éventuelles contraintes et spécificités concernant les conditions techniques de production, d'exploitation et de qualité d'une <strong class="underline uppercase">prestation</strong>. Le <strong class="underline uppercase">cahier des charges</strong> ne constitue un élément contractuel qu'à partir de l'instant où il est signé par les 2 parties. Tout <strong class="underline uppercase">cahier des charges</strong> non signé ou signé uniquement par l'une des parties est considéré comme nul.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 1 : Objet - Domaine d'application</h2><br/>
    <p>Les Conditions Générales ont pour objet de régir les relations contractuelles entre <strong class="underline uppercase">LE PRESTATAIRE</strong> et le <strong class="underline uppercase">CLIENT</strong> et définir l'étendue des <strong class="underline uppercase">prestation</strong>s proposées par <strong class="underline uppercase">LE PRESTATAIRE</strong>.</p>
    <p>Les Conditions Générales s'appliquent à toute <strong class="underline uppercase">prestation</strong> de toute nature, effectuée par <strong class="underline uppercase">LE PRESTATAIRE</strong> dans les pays du monde entier. Elles prévalent sur toute autre condition d'achat, sauf dérogation expresse et formelle accordée par <strong class="underline uppercase">LE PRESTATAIRE</strong>. Elles pourront être modifiées ou complétées si <strong class="underline uppercase">LE PRESTATAIRE</strong> établit un ou plusieurs éléments contractuels qui, le cas échéant, tiendraient lieu de conditions particulières.</p>
    <p>Le fait pour une personne physique ou morale, de commander un service ou produit au <strong class="underline uppercase">PRESTATAIRE</strong> emporte acceptation pleine et entière des présentes Conditions Générales.</p>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> peut modifier, réactualiser ou rectifier les présentes, notamment afin de prendre en compte une évolution législative, réglementaire, jurisprudentielle et/ou technique. <strong class="underline uppercase">LE PRESTATAIRE</strong> prévient, dans la mesure du possible, ses <strong class="underline uppercase">CLIENT</strong>S de toute modification de ses Conditions Générales, soit sur la page d'accueil de son site Internet (accessible à l'URL suivante http://www.espace- technologie.com/), soit par le biais d'un affichage au siège social (situé à l'adresse indiquée dans le préambule). L'actualisation ne concerne en aucun cas les <strong class="underline uppercase">prestation</strong>s déjà exécutées ou en cours d'exécution, sauf pour celles dont la durée restante est supérieure à six mois à la date de la modification. Dans ce cas les dernières Conditions Générales sont mises en application entre les parties.Dans le cas où l'une des dispositions des présentes est réputée ou déclarée nulle, ou non écrite, par un tribunal compétent, les autres dispositions restent intégralement en vigueur et doivent être interprétées de façon à respecter l'intention originelle des parties.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 2 : Formation et conditions d'exécution du contrat</h2><br/>
    <p>L'obligation respective de chaque partie, de réaliser la <strong class="underline uppercase">prestation</strong> pour <strong class="underline uppercase">LE PRESTATAIRE</strong> et de payer la <strong class="underline uppercase">prestation</strong> pour le <strong class="underline uppercase">CLIENT</strong>, naît à partir du moment où le <strong class="underline uppercase">CLIENT</strong> a dûment signé et retourné par fax, email ou courrier le ou les document(s) contractuel(s) émis par <strong class="underline uppercase">LE PRESTATAIRE</strong> ou à partir de l'encaissement d'un acompte initial par <strong class="underline uppercase">LE PRESTATAIRE</strong>. Si un devis a été établi, la demande de réalisation de la <strong class="underline uppercase">prestation</strong> décrite au devis vaut acceptation par le <strong class="underline uppercase">CLIENT</strong>.</p>
    <p>L'investissement personnel du <strong class="underline uppercase">CLIENT</strong> dans la création du site est indispensable sans quoi un résultat qui ne correspondrait pas à ses attentes ne saurait relever de la responsabilité du <strong class="underline uppercase">PRESTATAIRE</strong>, comme indiqué à l'article 5 ci-dessous.</p>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> peut décider de refuser, d'interrompre ou de modifier la <strong class="underline uppercase">prestation</strong> et ce, sans indemnités au profit du <strong class="underline uppercase">CLIENT</strong> ni remboursement d'acompte, dès l'instant où :</p>
    <ul>
      <li>Le <strong class="underline uppercase">CLIENT</strong> ne s'acquitte pas des sommes facturées par <strong class="underline uppercase">LE PRESTATAIRE</strong>;</li>
      <li>Le <strong class="underline uppercase">CLIENT</strong> ne démontre pas, ou plus, un gage suffisant de solvabilité;</li>
      <li>Lorsque le <strong class="underline uppercase">CLIENT</strong> ne présente pas ou plus les compétences nécessaires et spécifiques à la réalisation complète de la <strong class="underline uppercase">prestation</strong>, soit parce que le <strong class="underline uppercase">CLIENT</strong> manifeste une opposition systématique aux conseils et <strong class="underline uppercase">prestation</strong>s prodigués par <strong class="underline uppercase">LE PRESTATAIRE</strong>, soit parce que le <strong class="underline uppercase">CLIENT</strong> se refuse à fournir les instructions ou <strong class="underline uppercase">sources</strong> nécessaires à la réalisation définitive de la <strong class="underline uppercase">prestation</strong>;</li>
      <li>Lorsque <strong class="underline uppercase">LE PRESTATAIRE</strong> constate tout acte de piratage, de fraude ou de non-respect des règles éthiques, juridiques ou morales de la profession, imputable au <strong class="underline uppercase">CLIENT</strong>.</li>
    </ul>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> se réserve le droit d'apporter des modifications non substantielles à ses <strong class="underline uppercase">prestation</strong>s, sans que cela ne vienne remettre en cause les liens contractuels ni les obligations entre les deux parties.</p>
    <p>Toute <strong class="underline uppercase">prestation</strong> de gestion de nom de domaine, hébergement, adresses mail notamment, fait l'objet d'une facturation annuelle à date anniversaire. En cas d'interruption à l'initiative du <strong class="underline uppercase">CLIENT</strong>, ou de transfert vers un autre <strong class="underline uppercase">PRESTATAIRE</strong> en cours d'année de l'une ou l'autre de ces <strong class="underline uppercase">prestation</strong>s, le règlement est dû pour l'ensemble de l'année en cours.</p>
    <p>Aucune commande d'une <strong class="underline uppercase">prestation</strong> ne peut être annulée sans l'accord express du <strong class="underline uppercase">PRESTATAIRE</strong>. A défaut, le <strong class="underline uppercase">CLIENT</strong> serait tenu de payer l'intégralité des sommes dues au <strong class="underline uppercase">PRESTATAIRE</strong>.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 3 : Prix - facturations - délais</h2><br/>
    <p>Le prix et les conditions de facturations sont indiqués sur le devis.</p>
    <p>Le prix de la <strong class="underline uppercase">prestation</strong> est ferme. Il est stipulé hors taxes et exprimé en euro portant sur le montant total à payer.</p>
    <p>Les conditions de l'offre concernent exclusivement les <strong class="underline uppercase">prestation</strong>s spécifiées sur le devis. Toute <strong class="underline uppercase">prestation</strong> supplémentaire et non prévue sur ce dernier fera l'objet d'une majoration équivalente à sa valeur. Le refus de paiement d'une telle <strong class="underline uppercase">prestation</strong> ouvrira le droit pour <strong class="underline uppercase">LE PRESTATAIRE</strong> à la résiliation et au paiement intégral du contrat de vente, et à une indemnité égale au préjudice subi et/ou à la valeur de la <strong class="underline uppercase">prestation</strong> additionnelle.</p>
    <p>En cas de défaut de paiement total ou partiel du prix de la <strong class="underline uppercase">prestation</strong> :</p>
    <p>Nous nous réservons la propriété jusqu'au paiement complet du prix par l'acheteur. Notre réserve de propriété porte aussi bien sur les marchandises que sur leur prix si elles ont déjà été revendues (Loi N° 80.335 du 12 Mai 1980).</p>
    <p>Le défaut de règlement le jour suivant la date de paiement figurant sur la facture entraîne, de plein droit et sans mise en demeure préalable, le paiement de pénalités de retard au taux minimum de trois fois le taux d'intérêt légal en vigueur.</p>
    <p>Toute contestation ou réclamation relative à la facturation doit être adressée par lettre recommandée dans les dix jours à réception de la dite facture, à défaut de quoi <strong class="underline uppercase">LE PRESTATAIRE</strong> n'accepte plus aucun grief.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 4 : Livraison de la <strong class="underline uppercase">prestation</strong></h2><br/>
    <p>Sauf stipulation expresse contraire, la livraison, quelle que soit la <strong class="underline uppercase">prestation</strong>, est effectuée au lieu du siège social du <strong class="underline uppercase">PRESTATAIRE</strong> sans formalité particulière. Dans un délai de deux semaines à partir de la date de livraison prévue, la livraison est réputée avoir eu lieu aux dates et conditions prévues.</p>
    <p>Les délais de livraison ne sont donnés qu'à titre indicatif.</p>
    <p>Lorsque le&nbsp; <strong class="underline uppercase">CLIENT</strong> ne&nbsp; transmet&nbsp; pas dans&nbsp; les délais&nbsp; convenus&nbsp; les éléments nécessaires à la bonne réalisation de la <strong class="underline uppercase">prestation</strong> (<strong class="underline uppercase">sources</strong>, <strong class="underline uppercase">cahier des charges</strong>, etc.), ce fait a pour conséquence directe de retarder la réalisation et donc la livraison de la <strong class="underline uppercase">prestation</strong> par <strong class="underline uppercase">LE PRESTATAIRE</strong>. Pour autant, <strong class="underline uppercase">LE PRESTATAIRE</strong> ne saurait en aucun cas être considéré comme responsable d'une situation qu'il subit en premier lieu. Dès lors, le <strong class="underline uppercase">CLIENT</strong> reste soumis à pénalité jusqu'à ce que les éléments nécessaires soient transmis, ou sera sanctionné conformément aux dispositions de l'article 2.</p>
    <p>Si lors de la livraison de la <strong class="underline uppercase">prestation</strong>, le <strong class="underline uppercase">CLIENT</strong> considère que la <strong class="underline uppercase">prestation</strong> n'est pas conforme au <strong class="underline uppercase">cahier des charges</strong>, il doit dans une période de deux mois à compter de la livraison, déclarer par écrit le dysfonctionnement des vices qu'il impute à la <strong class="underline uppercase">prestation</strong>, et fournir toute justification quant à la réalité de ceux-ci. En cas de réclamation sur une <strong class="underline uppercase">prestation</strong> essentiellement immatérielle (site Internet, solution de gestion, application métier etc) le <strong class="underline uppercase">cahier des charges</strong> reste le document de référence auquel les deux parties doivent se référer pour évaluer si la <strong class="underline uppercase">prestation</strong> est conforme aux spécificités du projet.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 5 : Responsabilités du <strong class="underline uppercase">PRESTATAIRE</strong></h2><br/>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> fera ses meilleurs efforts pour apporter tout le soin et la diligence nécessaires à la fourniture d'un service de qualité conformément aux usages de la profession et à l'état de l'art. <strong class="underline uppercase">LE PRESTATAIRE</strong> ne répond que d'une obligation de moyens qui ne doit en aucun cas être assimilée à une obligation de résultat.</p>
    <p><em>Limitations de responsabilités</em></p>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> ne pourra être tenu responsable en cas de :</p>
    <ul>
      <li>Faute, négligence, omission ou défaut d'entretien du <strong class="underline uppercase">CLIENT</strong>, non-respect des conseils donnés :</li>
    </ul>
    <p>En particulier, lorsque <strong class="underline uppercase">LE PRESTATAIRE</strong> réalise des <strong class="underline uppercase">prestation</strong>s d'hébergement, il conserve le contrôle des accès FTP. Cependant, dès lors que le <strong class="underline uppercase">CLIENT</strong> dispose desdits accès FTP, <strong class="underline uppercase">LE PRESTATAIRE</strong> est automatiquement dégagé de toute responsabilité quant à l'indisponibilité des pages, la nature du contenu (non-respect du droit d'auteur notamment), le défaut d'affichage, la détérioration partielle ou totale du contenu des pages.</p>
    <p>De manière générale, <strong class="underline uppercase">LE PRESTATAIRE</strong> n'est en aucune façon responsable d'un dysfonctionnement résultant d'une mauvaise utilisation du <strong class="underline uppercase">CLIENT</strong> ou d'une intervention du <strong class="underline uppercase">CLIENT</strong> sans autorisation sur la <strong class="underline uppercase">prestation</strong> effectuée par <strong class="underline uppercase">LE PRESTATAIRE</strong>.</p>
    <ul>
      <li>Interruption de l'hébergement;</li>
      <li>Faute, négligence ou omission d'un tiers sur lequel <strong class="underline uppercase">LE PRESTATAIRE</strong> n'a aucun pouvoir de contrôle de surveillance.</li>
    </ul>
    <p>En particulier, lorsque <strong class="underline uppercase">LE PRESTATAIRE</strong> fournit des liens vers d'autres sites, par des bandeaux publicitaires ou non, ou par tout autre moyen, il ne peut être tenu responsable du contenu, des produits, des services, de la publicité, des cookies ou tous autres éléments de ces sites ainsi que pour tous dommages ou pertes, avérés ou allégués, consécutifs ou en relation avec l'utilisation des informations, services ou données disponibles sur ces sites;</p>
    <ul>
      <li>Divulgation ou utilisation illicite du mot de passe remis confidentiellement au <strong class="underline uppercase">CLIENT</strong> ;</li>
      <li>Dysfonctionnement ou ralentissement des réseaux ou de l'Internet dans son ensemble.</li>
    </ul>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 6 : Propriétés intellectuelles</h2><br/>
    <p>Tout élément fourni par le <strong class="underline uppercase">CLIENT</strong> est protégé par le droit de la propriété intellectuelle et reste sa seule propriété. Il déclare disposer de tous les droits et/ou autorisations nécessaires, et garantit <strong class="underline uppercase">LE PRESTATAIRE</strong> contre toute réclamation éventuelle d’un tiers qui prétendrait avoir un droit de propriété intellectuelle sur l’un quelconque des éléments fournis par lui notamment de tous textes, images, logos, graphiques, photos, films audio ou vidéo, fichiers, logiciels, bases de données.</p>
    <p>Le <strong class="underline uppercase">CLIENT</strong> est propriétaire du contenu c'est à dire des informations se trouvant sur son site (logo, pages HTML, fichiers images, sons ...), des bases de données, fichier <strong class="underline uppercase">CLIENT</strong>s ou autres.</p>
    <p>L'ensemble des créations du <strong class="underline uppercase">PRESTATAIRE</strong> restent sa propriété exclusive, et <strong class="underline uppercase">LE PRESTATAIRE</strong> se réserve le droit de revendre ou d'utiliser tout ou partie de ses créations. Ainsi, tout logiciel, application métier, ou autres développements spécifiques réalisés pour le <strong class="underline uppercase">CLIENT</strong> reste la propriété du <strong class="underline uppercase">PRESTATAIRE</strong>. Les droits d'exploitation de ces créations ne sont donc cédés au <strong class="underline uppercase">CLIENT</strong> qu'à titre non exclusif.</p>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> donne l'autorisation au <strong class="underline uppercase">CLIENT</strong>, lors d'une <strong class="underline uppercase">prestation</strong> immatérielle de modifier ou améliorer le code source existant, aux conditions impératives de ne pas revendre ou dupliquer les <strong class="underline uppercase">sources</strong>. Dans ce cas le <strong class="underline uppercase">CLIENT</strong> est le seul responsable des modifications ou améliorations et donc ne peut en aucune manière engager la responsabilité du <strong class="underline uppercase">PRESTATAIRE</strong> comme indiqué à l'article 5 des présentes.</p>
    <p>Lorsque <strong class="underline uppercase">LE PRESTATAIRE</strong> acquiert un ou plusieurs noms de domaine dans le cadre d'une <strong class="underline uppercase">prestation</strong> Internet, ces noms de domaines sont achetés au nom et pour le compte du <strong class="underline uppercase">CLIENT</strong>. Celui-ci peut demander à tout moment le transfert à ses propres coordonnés de la propriété des domaines, sous réserve du règlement au <strong class="underline uppercase">PRESTATAIRE</strong> des sommes dues au titre de la <strong class="underline uppercase">prestation</strong> pour laquelle les noms de domaines ont été acquis et plus généralement du règlement de l'ensemble des sommes dues au <strong class="underline uppercase">PRESTATAIRE</strong>. A défaut, le <strong class="underline uppercase">CLIENT</strong> entre dans les dispositions des articles 3, 4 et 7 des présentes et s'expose notamment à la revente ou au non-renouvellement des domaines.</p>
    <p>Tout le contenu du site du <strong class="underline uppercase">PRESTATAIRE</strong> est l'entière propriété du <strong class="underline uppercase">PRESTATAIRE</strong>, et est protégé par la législation en vigueur sur le droit d'auteur et sur la propriété intellectuelle. Sans accord préalable de la part du <strong class="underline uppercase">PRESTATAIRE</strong>, il est interdit d'utiliser, même partiellement le contenu du site.La violation de ces dispositions peut entraîner l'annulation de toute commande, ce nonobstant l'engagement de poursuites.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 7 : Réserve de propriété</h2><br/>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> conserve l'entière propriété de la <strong class="underline uppercase">prestation</strong> et de chacun de ses éléments, y compris immatériel, jusqu'au paiement effectif de l'intégralité du prix et accessoires et plus généralement jusqu'au règlement total de toute facturation due par le <strong class="underline uppercase">CLIENT</strong> à la société <strong class="underline uppercase">PRESTATAIRE</strong>.</p>
    <p>Dans le cas où une <strong class="underline uppercase">prestation</strong> fait l'objet d'une interruption définitive, que celle-ci soit à l'initiative du <strong class="underline uppercase">CLIENT</strong> ou du <strong class="underline uppercase">PRESTATAIRE</strong>, <strong class="underline uppercase">LE PRESTATAIRE</strong> a toute latitude, après avoir informé son <strong class="underline uppercase">CLIENT</strong>, de vendre, de détruire, de renouveler pour son propre compte ou celui de tiers, ou de ne pas renouveler tout actif inclus dans la <strong class="underline uppercase">prestation</strong>.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 8 : Utilisation des références</h2><br/>
    <p>Le <strong class="underline uppercase">CLIENT</strong> autorise <strong class="underline uppercase">LE PRESTATAIRE</strong> à utiliser son nom et à mentionner les <strong class="underline uppercase">prestation</strong>s réalisées pour son compte à des fins commerciales.</p>
    <p><strong class="underline uppercase">LE PRESTATAIRE</strong> se réserve le droit de faire mention de sa qualité de créateur du site Internet, et d'implanter son logo sur l'ensemble des <strong class="underline uppercase">prestation</strong>s crées pour le <strong class="underline uppercase">CLIENT</strong>, notamment au sein des sites Internet.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 9 : Loi informatique et liberté</h2><br/>
    <p>Le <strong class="underline uppercase">CLIENT</strong> s'engage expressément à assurer lui-même l'ensemble des formalités obligatoires à accomplir auprès de la CNIL (Commission Nationale de l'Informatique et des Libertés).</p>
    <p>Conformément à la loi informatique et liberté du 6 janvier 1978 (art. 34), le <strong class="underline uppercase">CLIENT</strong> dispose d'un droit permanent d'accès, de modification, de rectification et de suppressions relatives aux informations le concernant.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 10 : Dispositions générales</h2><br/>
    <p><em>Divisibilité</em></p>
    <p>Si l’une quelconque des stipulations du présent contrat s’avérait nulle au regard d’une règle de droit en vigueur ou d’une décision judiciaire devenue définitive, elle serait alors réputée non écrite, sans pour autant entraîner la nullité du contrat ni altérer la validité de ses autres dispositions. Le fait que l’une ou l’autre des parties ne revendique pas l’application d’une clause quelconque du contrat ou acquiesce à son inexécution, que ce soit de manière permanente ou temporaire, ne pourra être interprété comme une renonciation par cette partie aux droits qui découlent pour elle de ladite clause. Dans ce cas, les parties devront dans la mesure du possible remplacer la disposition annulée par une disposition valable correspondant à l’esprit et à l’objet des conditions contractuelles.</p>
    <p><em>Intitulés</em></p>
    <p>Les intitulés des articles des conditions contractuelles ont pour seul but de faciliter les références et n’ont pas par eux-mêmes, une valeur contractuelle ou une signification particulière.</p>
    <p><em>Notifications</em></p>
    <p>Toutes les notifications, communications, mises en demeure prévues par les conditions générales seront réputées avoir été valablement délivrées au <strong class="underline uppercase">CLIENT</strong> si elles sont adressées par lettre recommandée avec demande d’avis de réception :</p>
    <ul>
      <li>pour AS-Turing : 13, rue de la Glacière – 42510 BALBIGNY</li>
      <li>pour le titulaire de l’hébergement : à l’adresse postale et/ou e-mail qu’il a fournie à AS-Turing.</li>
    </ul>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 11 : Loi Applicable et attribution de juridiction</h2><br/>
    <p>La loi française sera seule applicable au présent contrat, à l’exclusion, d’une part, des règles de conflit prévues par la loi française, et d’autre part, des dispositions de la loi française qui seraient contraires au présent contrat. Tout litige entre les parties, relatif à leurs relations contractuelles et notamment à l’interprétation, l’exécution et la résiliation du présent contrat, sera soumis au tribunal de commerce du siège du <strong class="underline uppercase">PRESTATAIRE</strong> même en cas d’appel en garantie ou de pluralité de défendeurs. Le simple fait d'accepter et de signer le devis concernant une <strong class="underline uppercase">prestation</strong> d'hébergement de site internet vaudra pour acceptation pleine et entière des présentes conditions contractuelles</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 12 : Evolution de logiciels tiers</h2><br/>
    <p>Le <strong class="underline uppercase">CLIENT</strong> se doit d’indiquer au <strong class="underline uppercase">PRESTATAIRE</strong> toutes évolutions des logiciels tiers qui seraient en lien avec le SITE WEB. Toutes adaptations du SITE WEB, test, correction d’incident dû au fait de l’évolution d’un logiciel tiers, seront à la charge financière du <strong class="underline uppercase">CLIENT</strong>.</p>
    <br/><br/><h2 class="text-2xl font-bold underline">Article 13 : Evolution de la législation.</h2><br/>
    <p>Dans le cas d’une évolution de la législation impliquant des modifications pour la mise en conformité du SITE WEB, les frais de développement seront à la charge du <strong class="underline uppercase">CLIENT</strong>. Le développement du SITE WEB étant antérieur à la nouvelle législation, <strong class="underline uppercase">LE PRESTATAIRE</strong> ne peut être tenu responsable d’une éventuelle impossibilité de mise en conformité avec la nouvelle législation.</p></div>
</template>

<style scoped>

</style>